import type { Metadata } from "next";
import Header from "@/components/Header";
import { checkRole } from "@/utils/roles";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Raisa | Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="flex justify-center mt-12 min-h-[calc(100vh-3rem)]">
        {children}
      </main>
    </>
  );
}
