export const keyWordsSEO = [
  "Raisa",
  "raisa",
  "رايسه",
  "رايسة",
  "Restaurant",
  "restaurant",
  "مطعم",
  "Restaurants",
  "restaurant",
  "مطاعم",
  "Saudi Arabia",
  "Saudi arabia",
  "saudi Arabia",
  "saudi arabia",
  "السعودية",
  "المملكة العربيةالسعودية",
  "Syrian",
  "syrian",
  "سوريا",
  "Syrian Restaurant",
  "Syrian restaurant",
  "syrian Restaurant",
  "syrian restaurant",
  "مطعم سوري",
  "Syrian Restaurants",
  "Syrian restaurants",
  "syrian Restaurants",
  "syrian restaurants",
  "مطاعم سوري",
  "مطاعم سورية",
  "Foods",
  "foods",
  "أكل",
  "طعام",
  "Syrian Foods",
  "Syrian foods",
  "syrian Foods",
  "syrian foods",
  "أكل سوري",
];

export const defaultDescription = "Raisa restaurant saudi arabia";
