import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Raisa | Meal edit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main>{children}</main>
    </>
  );
}
